name: 登录测试

on:
  #将下面两行代码取消注释
  #schedule:
    #- cron: "0 0 * * *"
  workflow_dispatch:
    inputs:

env:
  PICA_ACCOUNT: ${{secrets.PICA_ACCOUNT}}
  PICA_PASSWORD: ${{secrets.PICA_PASSWORD}}
  PICA_TOKEN: ${{secrets.PICA_TOKEN}}
  PICA_SECRET_KEY: ${{secrets.PICA_SECRET_KEY && '~d}$Q7$eIni=V)9\\RK/P.RM4;9[7|@/CA}b~OW!3?EV`:<>M7pddUBL5n|0/*Cn' }}


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: install dependency
        run: |
          pip install urllib3
          pip install requests
      
      - name: main logic
        run: |
          python login.py

      - name: upload-artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: token
          path: /
          # 压缩包14天后会被清除
          retention-days: 14
      
      # - name: commit & push
      #   uses: actions-go/push@master
      #   with:
      #     author-email: 'actions@github.com'
      #     author-name: 'GitHub Actions'
      #     commit-message: 'update downloaded comics'
      #     token: ${{ secrets.GITHUB_TOKEN }}
