name: 登录测试

on:
  #将下面两行代码取消注释
  #schedule:
    #- cron: "0 0 * * *"
  workflow_dispatch:
    inputs:

env:
  PICA_SECRET_KEY: ${{secrets.PICA_SECRET_KEY}}
  PICA_ACCOUNT: ${{secrets.PICA_ACCOUNT}}
  PICA_PASSWORD: ${{secrets.PICA_PASSWORD}}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: install dependency
        run: |
          pip install urllib3
          pip install requests
      
      - name: main logic
        run: |
          python login.py

      # comics文件夹下的所有漫画都会被打成一个压缩包,并上传到actions artifact. 如果不配置邮箱推送功能,可以用这个来下载到漫画
      - name: upload-artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: pica-comics
          path: comics/
          # 压缩包14天后会被清除
          retention-days: 14
      
      - name: commit & push
        uses: actions-go/push@master
        with:
          author-email: 'actions@github.com'
          author-name: 'GitHub Actions'
          commit-message: 'update downloaded comics'
          token: ${{ secrets.GITHUB_TOKEN }}
